<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <LangVersion>14</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.8" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Koko.Native\Koko.Native.vcxproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Docs\**\*">
      <LinkBase>Docs</LinkBase>
    </None>
  </ItemGroup>

</Project>
